Repository mistweaverco/bananas, pull requests merged in 2024-12, with the labels that each got.

#23 perf(url): compress urls
  src/renderer/src/App.svelte
  src/renderer/src/Host.svelte
  src/renderer/src/Join.svelte
  src/renderer/src/Utils.ts
  src/renderer/src/WebRTC.svelte
Labels: enhancement

#24 feat(ux): don't crash on non-existing microphone
  package.json
  src/renderer/src/WebRTC.svelte
Labels: enhancement

#26 feat(ux): make iceServers configurable
  src/main/stateKeeper.ts
  src/preload/index.ts
  src/renderer/src/Config.ts
  src/renderer/src/Settings.svelte
  src/renderer/src/WebRTC.svelte
  src/renderer/src/env.d.ts
Labels: enhancement

#27 feat(settings): make turn auth possible
  src/main/stateKeeper.ts
  src/preload/index.ts
  src/renderer/src/Config.ts
  src/renderer/src/Settings.svelte
  src/renderer/src/env.d.ts
Labels: enhancement

#32 ui: move gh links, add minimum w/h
  src/main/index.ts
  src/renderer/src/App.svelte
  src/renderer/src/Navigation.svelte
  src/renderer/src/Settings.svelte
  src/renderer/src/Utils.ts
Labels: enhancement

#51 Implements windows install for all users
  electron-builder.yml
Labels: enhancement

#53 docs: add brew instructions for mac to readme
  README.md
Labels: documentation

#54 fix(docs): TOS LICENSE link
  TOS.md
Labels: documentation

#55 Feat/about view
  .prettierignore
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  TOS.md
  src/main/ipcMainHandlers.ts
  src/preload/index.d.ts
  src/preload/index.ts
  src/renderer/src/About.svelte
  src/renderer/src/App.svelte
  src/renderer/src/Navigation.svelte
  src/renderer/src/Settings.svelte
  src/renderer/src/env.d.ts
Labels: enhancement

#56 Feat/settings mic state on join
  src/main/stateKeeper.ts
  src/preload/index.d.ts
  src/preload/index.ts
  src/renderer/src/BananasTypes.ts
  src/renderer/src/Host.svelte
  src/renderer/src/Join.svelte
  src/renderer/src/Settings.svelte
  src/renderer/src/WebRTC.svelte
  src/renderer/src/env.d.ts
Labels: enhancement

#57 fix(ui): hide audio element
  src/renderer/src/WebRTC.svelte
Labels: bug

#58 fix: use correct links href
  src/renderer/src/About.svelte
Labels: bug

#66 feat(ci): add flatpak to releases
  .github/workflows/release.yaml
  electron-builder.yml
  package.json
  scripts/release.sh
Labels: enhancement, linux

#59 UX: Audio Indicator
  package.json
  src/renderer/src/About.svelte
  src/renderer/src/AudioVisualizer.svelte
  src/renderer/src/Host.svelte
  src/renderer/src/Join.svelte
  src/renderer/src/Utils.ts
  src/renderer/src/WebRTC.svelte
Labels: enhancement

#64 feat: migrate to bun from npm
  .github/workflows/release.yaml
  bun.lockb
  package-lock.json
  package.json
  scripts/build.sh
Labels: enhancement

#67 feat(ci): cache dependencies
  .github/workflows/release.yaml
Labels: enhancement

#68 feat(ux): notify on connect, fail and close
  bun.lockb
  package.json
  src/renderer/src/Host.svelte
  src/renderer/src/Join.svelte
  src/renderer/src/WebRTC.svelte
  src/renderer/src/main.ts
  src/renderer/src/overrides.css
Labels: enhancement

#70 feat(docs): add shoulders-of-giants to about
  src/renderer/src/About.shoulders-of-giants.json
  src/renderer/src/About.svelte
Labels: documentation

#71 fix(about): use correct gh links
  src/renderer/src/About.svelte
Labels: documentation

#72 feat(docs): add discord to shoulders-of-giants
  src/renderer/src/About.shoulders-of-giants.json
  src/renderer/src/About.svelte
Labels: documentation
